/**
 * Plain-language explainers, keyed by section kind — the ONE dictionary
 * behind both comprehension surfaces:
 *
 *   1. the in-flow "In plain terms" line under every viz section
 *      (core/Section.astro; an authored `section.plain` overrides `what`), and
 *   2. the ⤢ expand-modal study view (core/ExpandModal.astro — serialized
 *      into its inline script as JSON).
 *
 * `what` explains the FORM of the graphic — how to read it, never the data
 * ("each stripe is one year's temperature", not "2023 was the hottest").
 * `how` is the interactive cue shown in the modal.
 *
 * New kinds MUST add an entry here (blueprint §9 supplies the wording; see
 * docs/design/blueprints/_TEMPLATE.md). Narrative kinds (hero, act-break,
 * prose, quote, beat-sheet, analogy, comparison) deliberately have none —
 * they explain themselves.
 */
export interface Explainer {
  what: string;
  how: string;
}

export const EXPLAIN: Record<string, Explainer> = {
  'orbit-globe': { what: 'A 3-D Earth showing the paths satellites travel. Each ring is one orbit at its real altitude and tilt; the coloured dots are satellites, and busier constellations carry more of them.', how: 'Drag to spin the globe — it keeps turning on its own. Country names fade in on the side facing you.' },
  'coalition-orbit': { what: 'Each political party circles the government at the centre as its own body. The bigger the sphere, the more seats that party holds.', how: 'Drag to rotate. Compare sphere sizes to see who holds the balance of power.' },
  'swing-dial': { what: 'A single needle that leans toward whichever of two sides is ahead — the further it tilts, the bigger the lead.', how: 'Read which side the needle points to, and how far over it has swung.' },
  'bill-passage': { what: 'The journey of a bill through every stage of becoming law, each step marked passed, failed, or still pending.', how: 'Follow the cards left to right to see how far it got and where it stalled.' },
  'vote-flow': { what: 'How each voting bloc’s seats flowed into “for”, “against”, or “abstain” — and whether the motion passed.', how: 'Follow a ribbon from a party to its vote; the thicker the ribbon, the more seats it carries.' },
  'margin-ladder': { what: 'Seats ranked by how comfortably they were won. The longer the bar, the bigger the winning margin.', how: 'Long bars are safe seats; the short bars at the bottom were the close contests.' },
  'chamber': { what: 'The chamber from above — every block is one seat, grouped by party. The dashed arc is the majority line.', how: 'Drag to look around. Hover any bloc for its numbers — and if a vote is attached, press DIVISION to watch the seats walk to the lobbies.' },
  'power-flow': { what: 'Money flows left to right — every band is one route, and thicker bands carry more. The moving dashes show direction.', how: 'Follow any band from its source to where it lands; the values are marked mid-stream.' },
  'coalition-calculus': { what: "Every block is one party's seats on a single bar; press parties in or out and the bar shows whether the group reaches the majority line.", how: 'Tap a party chip to add it to the coalition — the readout keeps honest score. Padlocked parties state why they can’t join.' },
  'gerrymander-lens': { what: 'The same voters, three ways of drawing the districts; each map shows who wins and how skewed it is — the number is the efficiency gap, and the fills never change.', how: 'Compare the three maps: the coloured cells are the same electorate in all three, only the black district lines move. The lower a plan’s efficiency-gap number sits from zero, the more the map favours one side.' },
  'ballot-flow': { what: 'Each column is one counting round; when a candidate is knocked out, the moving ribbons show where their votes went next, and the dashed line is the majority needed to win.', how: 'Read left to right, round by round. Follow a ribbon from an eliminated candidate to see who picked up their votes; ballots with no next choice flow to the muted exhausted lane.' },
  'solar-system': { what: 'A top-down map of the solar system — each ring is one real orbit, each dot a body at its actual position for the story’s date. The amber object is the one this story follows.', how: 'Drag to tilt and spin, scroll to zoom. Hover any body for its distance and year-length.' },
  'constellation-swarm': { what: 'Each dot is one satellite on its real orbital shell around Earth; the whole cloud is the constellation at true scale. Colour groups the shells.', how: 'Drag to orbit the swarm, scroll to zoom. Hover any satellite for its shell’s altitude, tilt, and true count.' },
  'lagrange-map': { what: 'The shaded landscape is the combined gravity-and-spin terrain of the two bodies; the five rings mark the points where the pulls balance — three are knife-edge, two are stable.', how: 'Read the contours like a topographic map: the two bodies sit in the deep wells, and L4/L5 are the shallow stable basins 60° ahead of and behind the smaller body.' },
  'transfer-window': { what: 'Two rings are the orbits, the arc between them is the cheapest transfer path, and the two dots must line up at the right angle for the trip to work.', how: 'Drag the slider to sweep the departure planet around its orbit. The cost and travel time never change — but only one phase angle actually arrives; that is the launch window.' },
  'eclipse-cone': { what: 'The dark cone is the full shadow the body casts; it tapers to a point at a real distance, and totality only happens where the target sits inside that point before it closes.', how: 'Compare the two discs top-right — the Sun and the Moon look almost exactly the same size from Earth, which is the only reason a total eclipse can happen.' },
  'trajectory-arc': { what: 'A rocket’s flight from launch to orbit — height climbs as it travels downrange, with each phase of the ascent pinned.', how: 'Trace the arc from liftoff (left) up to orbital insertion (right).' },
  'delta-v-ladder': { what: 'The “fuel budget” (delta-v) it takes to climb from one orbit to the next, stacked into a ladder. Taller blocks need more energy.', how: 'Each block is one leg of the climb; the whole stack is the full trip to escape.' },
  'signal-readout': { what: 'Signal strength across different radio bands, like a mission-control telemetry panel.', how: 'Each bar’s fill shows how strong that band’s signal is right now.' },
  'descent-profile': { what: 'A spacecraft’s altitude over time as it lands — the curve falls as it drops, with the critical moments pinned.', how: 'Read left (high and fast) to right (touchdown).' },
  'terrain-relief': { what: 'The real shape of the ground, drawn as contour rings and ridgelines — each ring joins points at the same height, and the brown lines trace the crests. The vertical scale is stretched to make the relief legible; the caption says by how much.', how: 'Drag to tilt the massif, scroll to zoom. Press the ×-scale button to swap between the true and the exaggerated height. Hover a peak for its elevation.' },
  'plate-motion': { what: 'Each arrow shows which way a tectonic plate is moving at that spot and how fast — longer means faster, and the arrows shrink to nothing at the point the plate pivots around. The heavy lines are the plate boundaries.', how: 'Drag to spin the globe. Hover any arrow for the exact speed and direction of the plate there.' },
  'atmosphere-column': { what: 'A slice of the sky stood on end, drawn to true height — each band is one layer of the atmosphere, the curve on the right is how fast the air pressure drops as you climb, and the pinned heights are places you already know.', how: 'Read bottom to top: ground level at the base, the edge of space at the top. The brown curve shows pressure falling away; the marks in the margin are landmark altitudes.' },
  'carbon-loop': { what: 'Each box is a place carbon is stored, sized by how much it holds; each arrow is a yearly flow between them, thicker and faster where more carbon moves. The brown mark shows the carbon that arrives but never leaves.', how: 'Follow the arrows around the loop — most nearly cancel out. Watch the brown residual on the atmosphere: that is the part that accumulates every year.' },
  'storm-track': { what: "One tropical cyclone's real path across the ocean, drawn from birth to breakup — the colour of the line is how strong it was at each point, from a weak depression to a top-category hurricane. The glowing point is its peak; the ringed points are where it hit land.", how: 'Drag to spin the globe and follow the track. Hover any point on the path for the exact wind speed, category, and date.' },
  'neural-flow': { what: 'Each column is one layer of the network and every dot is one unit, at true layer sizes. The lime wave is a single forward pass moving from input to answer.', how: 'Drag to look around the layers. Hover any column for its unit and weight counts.' },
  'packet-trace': { what: 'The globe shows the actual path a request takes between cities; the bar below splits the round-trip time into the part physics forces (green) and the part everything else adds (pink).', how: 'Drag to spin the globe. Hover any bar segment to light up that leg of the journey and see how far it ran over the physical minimum.' },
  'queue-cliff': { what: 'The curve is how long the average request waits as the system fills up — it stays flat, then snaps vertical as load nears full capacity.', how: 'Drag the slider to raise the load. Watch the wait multiplier stay calm, then explode past about 90% — the readout gives the exact numbers.' },
  'chip-die': { what: 'A processor die as an exploded, to-scale floorplan: each tile is one functional block, and its size on screen equals its real share of the silicon.', how: 'Hover or tap a tile to lift it and read its area. The biggest tiles are where the chip actually spends its space.' },
  'moore-ladder': { what: 'How a technology’s count — like transistors per chip — explodes over the years, drawn on a ruler where each step up means twice as many, so the exponential becomes a straight climb.', how: 'Read up the ladder: every rung is double the last, and the straight line is the steady doubling. Hover any chip for its exact count.' },
  'terminator-globe': { what: 'A real globe lit for one moment — the shaded half is night, the line across it is where day meets dark, and the terracotta arc is your flight crossing from one into the other.', how: 'Drag to spin the Earth; scroll to zoom. Hover either city for its local clock — and press ARRIVAL to jump the sun forward to when you land.' },
  'city-grid': { what: "Each city is a compass wheel of 36 spokes; a spoke's length is how much of that city's streets run in that direction, so a planned grid draws a sharp cross and an old tangle draws a near-circle.", how: 'Compare the silhouettes: a sharp four-spoke cross is a surveyor grid, a full circle is organic streets. The order φ number sums it up.' },
  'altitude-oxygen': { what: "Height runs up the side; the column's width is how much oxygen the air still carries at that height. Each dot is a stop on the climb, and the teal tents mark the nights spent letting the body catch up.", how: 'Read up the column — the higher you go, the thinner it gets. The marked stops show where the trek pauses to acclimatize.' },
  'season-wheel': { what: "A destination's whole year as a tilted dial — twelve month-sectors, each with three stacked arcs for how good the weather is, how thick the crowds are, and how high the prices climb.", how: 'Slide through the months — the wheel lights each one and reads out its numbers. The marked arc is the sweet spot.' },
  'fare-terrain': { what: "Each ridge is one route's fare as departure nears — time runs left to right toward the flight, and higher ground means a pricier ticket. The shaded valley is the window where fares bottom out.", how: 'Follow a ridge from far-out on the left to the flight on the right; the low point in the shaded band is when to book.' },
  'flight-of-the-ball': { what: 'The bright line is the ball’s real curved flight; the faint dashed line is the straight path it would have taken with no air. The gap between them is how much the spin bent it.', how: 'Drag to look around the shot, scroll to zoom. Press REPLAY to watch the ball fly the arc again.' },
  'elo-river': { what: "Each coloured ribbon is one team, and how thick it is shows its rating; the ribbons stack and weave, so a team climbing past another crosses over it in the braid.", how: "Follow any ribbon left to right across the season; the volt one is the team this story is about." },
  'court-value': { what: "The pitch shaded by how much a shot from each spot is worth — the brighter the volt, the better the chance from there.", how: "Read it like a height map: the bright core is where chances are most valuable, and each contour line steps down to a lower value." },
  'pace-ridge': { what: "Each stacked shape is one group's whole range of the measured stat: wider where more of them cluster, with a line marking the middle. The volt shape is the athlete this story follows.", how: "Read each ridge as a range, not a single number — the hump is where most values fall, and the marked line is the middle." },
  'data-globe': { what: 'A 3-D Earth with a bubble on each place. The bigger the bubble, the bigger that place’s value for whatever is being measured.', how: 'Drag to spin; compare bubble sizes across regions.' },
  'core-sample': { what: 'A core drilled into ice or rock, read top (most recent) to bottom (most ancient). Each band is a layer of time.', how: 'Scan down the column to travel further into the past.' },
  'sea-level-tank': { what: 'A cross-section of rising water, with a marked line for each future sea-level scenario.', how: 'The higher the water line, the worse the scenario it represents.' },
  'climate-spiral': { what: 'Temperature for every month, spiralling outward as the years pass. The wider and redder the spiral grows, the more it has warmed.', how: 'Follow the line outward from the centre through time.' },
  'quake-depth': { what: 'Every earthquake plotted by how deep underground it struck and when. Bigger circles are stronger quakes.', how: 'Lower down = deeper; bigger = stronger. Hover a circle for its details.' },
  'arch-stack': { what: 'The layers of a software system stacked like floors of a building — from what users touch at the top down to the infrastructure beneath.', how: 'Top is the front-end; each layer below it is what powers the one above.' },
  'latency-waterfall': { what: 'How long each step of a request takes, laid end-to-end on a timeline. Longer bars are the slower steps.', how: 'Left to right is time elapsed; the longest bar is the bottleneck.' },
  'version-graph': { what: 'A project’s history as a branching tree of commits and releases.', how: 'Follow the line down through time; branches split off and merge back in.' },
  'scaling-plot': { what: 'How performance changes as something grows — for example, model size against accuracy — plotted on a scaling curve.', how: 'Up-and-to-the-right means it keeps improving as it scales.' },
  'throughput-dial': { what: 'A speedometer for how many requests a system handles each second, against its maximum capacity.', how: 'The fuller the arc, the closer the system is to its limit.' },
  'route-globe': { what: 'A 3-D Earth with the flight paths between the cities on a journey, drawn as great-circle arcs.', how: 'Drag to spin; the arcs connect each stop in travel order.' },
  'elevation-trek': { what: 'The ups and downs of elevation along a route — a side-view of the terrain you’d cross.', how: 'Peaks are climbs and dips are descents; left to right is distance travelled.' },
  'itinerary-reel': { what: 'A trip broken into day-by-day cards, each listing what happens that day.', how: 'Move through the days left to right.' },
  'climate-calendar': { what: 'A month-by-month picture of a place’s weather — the typical temperature and rainfall for each month of the year.', how: 'Warmer colours mark hotter months; taller bars mark wetter ones.' },
  'timezone-arc': { what: 'Where it is day or night across several cities at this moment, laid along a 24-hour band.', how: 'Light means daytime, dark means night — read each city’s local time.' },
  'tactics-pitch': { what: 'A team’s shape on the pitch, with every player placed in their position and seen at an angle.', how: 'Drag to rotate the pitch; each disc is a player in their starting spot.' },
  'shot-map': { what: 'Every shot at goal plotted where it was taken. Bigger marks were better chances (higher “xG”).', how: 'Closer to goal and bigger = a better chance; the colour shows what happened.' },
  'xg-race': { what: 'Two teams’ chances stacking up minute by minute. The higher line created the better openings.', how: 'A steeper climb means a spell of strong chances for that team.' },
  'momentum-wave': { what: 'Which team was on top through the match — the wave swells toward whoever was pressing.', how: 'Above the centre line means the home side was on top; below means the away side.' },
  'player-card': { what: 'A player’s headline rating with their key attributes — flip the card for the full breakdown.', how: 'Press Flip to turn the card over and see every stat.' },
  'approval-chart': { what: 'Two lines tracking approval against disapproval over time. Where they cross is the moment opinion flipped.', how: 'A rising accent line means growing approval.' },
  'power-matrix': { what: 'A grid of who controls which institution. Filled cells are full control, hatched cells partial, empty ones none.', how: 'Read each row (an institution) across the columns (the parties).' },
  'paradox': { what: 'Two sides of a contradiction set side by side so you can weigh the competing claims directly.', how: 'Compare the left panel against the right; the pivot marks the tension between them.' },
  'timeline': { what: 'The key events in order down a rail, with coloured dots flagging the pivotal moments.', how: 'Follow the rail from top to bottom through time.' },
  'vote-result': { what: 'How a vote split for against, the threshold it needed to pass, and a chamber showing every member.', how: 'Each dot is one member; the dashed line is the bar the motion had to clear.' },
  'climate-strip': { what: 'Each stripe is one year’s temperature — cooler years blue, warmer years red — with a line tracing the trend.', how: 'Left (past) to right (now); the redder it gets, the hotter the year.' },
  'benchmark-chart': { what: 'Scores compared as horizontal bars, with a reference line for context. Longer is better.', how: 'Compare each bar’s length against the dashed reference mark.' },
  'adoption-curve': { what: 'How fast something caught on over time, following the classic S-shaped adoption curve, with milestones marked.', how: 'The steep middle section is the fast-growth phase.' },
  'route-card': { what: 'A multi-leg journey laid out stop by stop, with the travel mode, distance and time for each leg.', how: 'Read top to bottom in travel order.' },
  'city-compare': { what: 'Two cities compared head-to-head across several measures, with the winner of each row highlighted.', how: 'Each row is one measure; the highlighted side wins it.' },
  'league-table': { what: 'A sports standings table — position, games, points and recent form for each team, with the qualification and relegation bands shaded.', how: 'Top rows make the cut; the shaded bottom rows drop out.' },
  'player-radar': { what: 'A player’s strengths across several skills, drawn as a shape. The bigger the shape, the more complete the player.', how: 'A wider, fuller shape means a stronger all-round player.' },
  'data-readout': { what: 'The headline numbers from the story, each with its unit and a one-line note.', how: 'Each tile is one key figure worth remembering.' },

  // Classic kinds without modal coverage historically — plain-line defaults
  // added 2026-07-05 so every viz gets an in-flow line.
  'seat-chart': { what: 'Seats or races listed with who holds them now and how that changed — the ledger of wins and losses.', how: 'Scan the change column for where the ground shifted.' },
  'bill-breakdown': { what: 'A bill or ruling broken into its key provisions, one card per provision.', how: 'Read the cards in order; the highlighted card is the one that matters most.' },
  'bill-funnel': { what: 'The same bills counted again at every stage they had to clear. Bar length is how many were still alive there, and the faded segment is what was lost since the row above.', how: 'Press a stage to read what happened there. The widening white space to the right of the bars is the real output of the session.' },
  'orbital-shells': { what: 'The layers of space around Earth, from low orbit outward, with what lives at each altitude.', how: 'Read outward from Earth: each shell is a different orbital neighbourhood.' },
  'orbit-trace': { what: 'A flat diagram of Earth ringed by named orbits, each drawn at its own altitude. The rings are spaced on a squeezed scale so the low and the distant fit together, and one satellite rides each ring.', how: 'Compare rings by how far they sit from Earth; the legend names each orbit and how many satellites share it.' },
  'launch-stats': { what: 'One column per year, split into a bar for each operator, so the height of a column is the total and the slices inside it show who flew.', how: 'Read left to right for the trend, and compare the coloured slices within a year to see who carried it.' },
  'commit-grid': { what: 'Activity over time as a grid of squares — each square is one day, darker means busier.', how: 'Read left to right through the weeks; dark streaks are the intense stretches.' },
  'journey-map': { what: 'The stops of a journey in order, with the story of each leg.', how: 'Follow the line from the first stop to the last.' },
  'match-stat-line': { what: 'The head-to-head numbers from one match, side by side.', how: 'Each row is one stat; the longer side won that battle.' },
  'elevation-profile': { what: 'Heights compared as vertical bands — how high each thing stands against the others.', how: 'Taller band = higher; the axis gives the scale.' },
  'region-map': { what: 'A map with the story’s regions shaded by category and key places pinned.', how: 'The legend decodes the shading; markers pin the named places.' },
  'carbon-gauge': { what: 'How much of the carbon budget is already spent, drawn as a gauge arc.', how: 'The filled arc is what’s used; the remainder is what’s left before the target.' },
};
