/**
 * explainers.ts entries for the 28 new kinds.
 *
 * Paste into EXPLAIN in src/lib/explainers.ts. Order does not matter there
 * (it is a Record, not a checked list), but keeping world groups together
 * matches the existing file.
 *
 * `what` explains the FORM — how to read it, never the data.
 * `how`  is the interactive cue shown in the ⤢ expand modal.
 *
 * For the 19 static kinds, `how` describes what to compare rather than what to
 * press — the modal always shows a `how` line, and "nothing to click" is not a
 * useful sentence.
 */

// ── politics
'majority-flow': { what: 'Every seat in the house enters on the left as one of several groups, merges into a bloc in the middle, and arrives on the right at the only question that matters — whether that bloc can pass a law alone. Ribbon thickness is seats, and the dashed line is the number needed.', how: 'Press any group to follow its seats through the flow. The readout answers what happens to the majority if that group walks out — which is how you find the partners the bloc cannot afford to lose.' },
'rank-bump': { what: 'Each line is one party and the only thing plotted is where it finished — first at the top, last at the bottom. Vertical distance is places, not votes, so a line can climb steeply on very few extra ballots.', how: 'Follow one line across the elections. Crossings are overtakes; a line that stays flat kept its position even if its vote share moved.' },
'bill-funnel': { what: 'The same set of bills counted again at every stage they had to clear, in order. Bar length is how many were still alive at that point, and the darker segment on each row is what was lost since the row above it.', how: 'Press a stage to read what happened there. The widening white space to the right of the bars is the real output of the session.' },
'age-pyramid': { what: 'One row per age band, oldest at the top, with bars running outward from the centre line — one sex to each side. Read it as counts to see the size of each band, or as shares to compare the balance inside bands of very different sizes.', how: 'Switch between counts and shares. Counts show where the members actually are; shares show whether the imbalance is a generational effect working through, or roughly constant.' },
'turnout-margin': { what: 'Each dot is one election, placed by turnout across the bottom and by the winner\u2019s margin up the side, joined in time order. This is a path rather than a trend — where it doubles back, the two numbers stopped moving together.', how: 'Trace the path in date order and watch for the reversal. Hover any dot for that election\u2019s two numbers and the change in margin.' },

// ── space
'mission-timeline': { what: 'One bar per mission phase, laid on a single clock that starts at launch, so bar length is real duration. The diamonds on the lower lane are the moments that cannot be rescheduled.', how: 'Press a phase or a milestone for its dates and its share of the mission. The phase drawn thinnest is usually the one everything else exists to deliver.' },
'porkchop-grid': { what: 'Departure dates run across the bottom, arrival dates up the side, and every cell is one pairing of the two. The colour is the velocity change that trip would need — brightest is cheapest — so the bright island is the launch window and everything outside it is a mission the rocket cannot perform.', how: 'Move across the grid for any pairing\u2019s exact cost and flight time. The readout also gives the penalty against the cheapest departure in the whole grid.' },
'debris-histogram': { what: 'Objects in orbit sorted into size bins, smallest on the left, on a scale where each gridline is ten times the one below it — so a bar one step taller means ten times as many objects, not twice.', how: 'Switch to trackable-only to see what radar can actually hold. The gap between the two views is the part of the hazard that no collision-avoidance system can see.' },
'margin-bullets': { what: 'One row per subsystem, each drawn on its own scale because decibels and kilograms do not compare. The bar is what the spacecraft has, the tick is what it is required to have, and a bar stopping short of its tick is a subsystem that does not close.', how: 'Compare each bar to its own tick, never to another row. The readout gives the signed margin against requirement in that row\u2019s unit.' },

// ── earth
'river-multiples': { what: 'One small panel per series, each showing a full year and each scaled to its own peak — so heights compare shapes, not volumes, and a small river can fill its box just as a large one does. What you are comparing is when the water arrives.', how: 'Scan the panels for the odd shape out, then press it for its real numbers. Panels are self-scaled, so never read one panel\u2019s height against another\u2019s.' },
'heat-uptake': { what: 'Stacked bands where the top edge of the whole shape is the total taken up and each band is one place it went. Absolute mode shows the total growing; share mode shows the split between the bands.', how: 'Switch between absolute and share. If the bands go flat in share mode, nothing is being redistributed — it is all simply getting larger.' },
'glacier-dumbbell': { what: 'Two dots per entity — hollow for the earlier survey, filled for the later one — with a bar between them for what was lost. The percentage is that same loss measured against the entity\u2019s own starting size.', how: 'Sort by share and by absolute loss. The two orders disagree, and which one you use decides which entity looks like it is in the most trouble.' },
'rain-calendar': { what: 'One row per month, one cell per day, darkest for the wettest. An annual total tells you nothing about this shape: the same rainfall could be a drizzle across every row or a handful of very dark cells.', how: 'Move across the grid for any single day\u2019s rainfall. The plain line counts how few days carry how much of the year.' },

// ── tech
'flame-graph': { what: 'The top bar is one request and every bar below it is a function called by the bar above. Width is the time spent inside that function and everything it called; depth is how deep in the stack it sits. Horizontal position means nothing — bars are nested, never ordered.', how: 'Press any frame to isolate its subtree and read total against self time. A wide bar low in the stack is the real cost, whatever the top of the profile says.' },
'latency-ridge': { what: 'One ridge per release, newest at the top, each showing how a day of requests was distributed across response times. The tick on each ridge is its median and the shaded foot is everything slower than the threshold.', how: 'Press a release to read its median and its share over the threshold together. A ridge that grows a second bump has developed a slow path the median cannot see.' },
'service-arcs': { what: 'Every service sits on one line in request order, and each arc is one service calling another with thickness for call volume. Arcs above the line run forwards; an arc below the line is a service calling something that was supposed to be upstream of it.', how: 'Press a service to keep only its arcs. Count the arcs below the line — that is the difference between a dependency graph and a dependency cycle.' },
'revenue-mosaic': { what: 'The whole rectangle is the total. Column width is what a segment contributes and the blocks inside it are how that segment splits, so block area is real money while block height is a share within its column only.', how: 'Press a column for its totals. A tall block in a narrow column is a big slice of a small pie — compare areas, not heights.' },
'state-timeline': { what: 'One lane per service across a single day, coloured by state rather than volume: healthy, degraded, or down. The numbered markers are the incident timeline.', how: 'Press a marker for its clock time and what happened. Then compare the lanes vertically to see what was already degraded before the first alert fired.' },

// ── travel
'attrition-waffle': { what: 'A hundred squares, one per person who started, grouped by where they stopped. Nothing is scaled or estimated — you can count the squares, and each colour block is exactly as many people as it looks like.', how: 'Press a group to isolate it and read why it stopped there. Counting the squares is the point: this is a rate you can audit.' },
'fare-spread': { what: 'One bar per month. The thin line is the full range of fares recorded, the solid bar is the middle half of them, and the notch is the median. A short bar means the month has one price; a long bar means booking date decides which end you get.', how: 'Press a month for its quartiles and its cheapest-to-dearest ratio. Compare a wide month\u2019s floor against a cheap month\u2019s ceiling — they often overlap.' },
'price-swarm': { what: 'One dot per observation, placed left to right by price. Dots are nudged vertically only so they do not sit on top of each other — height carries no meaning. Where the dots pile up is where the market actually is.', how: 'Move across the swarm for any single observation. The two marked lines are the mean and the median; the distance between them is what the outliers are doing to the average.' },
'route-criteria': { what: 'Five vertical axes, one per criterion, each scaled so its own best value is at the top. Every route is a line crossing all five, and crossing lines mean those two routes disagree on that pair of criteria.', how: 'Press a route to trace it and see where it dips. If every pair of lines crosses somewhere, there is no best route — only different things to want.' },
'daylight-band': { what: 'The shaded band is the time between sunrise and sunset across the year; everything above and below it is dark. The band\u2019s thickness is usable hours and its position is when they happen.', how: 'Switch latitude to see the band widen or flatten. At low latitudes the thickness barely changes but the whole band shifts — the light moves rather than shrinks.' },

// ── sports
'knockout-bracket': { what: 'Teams enter on the left and one leaves on the right; every fork is a match and the surviving line carries on. Line thickness is how likely the bookmakers thought that survival was before kick-off, so a thin line reaching the right-hand side is an upset nobody priced.', how: 'Press a team to trace its whole run. Compare how thick each winner\u2019s line was — the thinnest line that keeps going is the story.' },
'volume-accuracy': { what: 'Each dot is a team, placed by how often it attempts something across the bottom and how often that attempt works up the side. The dashed lines are the averages, cutting the chart into four quadrants; dot size is the resulting total.', how: 'Find which quadrant a team sits in, then check the dot size — it is the two axes multiplied out, so a small dot in the top-left is accuracy without enough volume to matter.' },
'goal-clock': { what: 'Two things on one frame. The bars count events in each block of match time on the left-hand scale; the line is the running share of all events by that minute on the right-hand scale. Where the line steepens, the bars are tall — the line is just the bars added up.', how: 'Press a block for its share and the cumulative total by then. Read the bars and the line separately: they use different scales on purpose.' },
'channel-ternary': { what: 'A triangle, because the three shares must add to a hundred and only two are ever free. Each corner is a team playing entirely down that channel and the centre point is a perfectly even split, so distance from a corner is how little a team uses it.', how: 'Press a dot for the three exact shares. A dot sitting near an edge means the channel opposite that edge is barely used at all.' },
'finish-interval': { what: 'The dot is the most likely finishing position and the bar is the range the model gives nine times out of ten. Overlapping bars mean the order between those teams is not yet decided by anything on the pitch.', how: 'Press a team to read its range and how many others overlap it. The shaded strips are the positions that carry a consequence.' },
