/**
 * Reactive pipeline — STAGE 3: route.
 *
 *   npm run reactive:route -- <topic|all>
 *
 * Takes un-routed, trending clusters → runs the news-classifier agent (Haiku,
 * reads _voice-core.md) → routes each to EITHER an issue candidate (a C-NN block
 * appended to research/<topic>/<date>-reactive-candidates.md, which the operator
 * merges into the human-gated editorial pipeline) OR a pending reactive social
 * post in /admin/social, or both, or ignore. Nothing auto-publishes or
 * auto-chooses.
 *
 * Bills ANTHROPIC_API_KEY (Haiku classifier). Needs PUBLIC_SUPABASE_URL +
 * SUPABASE_SERVICE_ROLE_KEY.
 */
import { readFileSync, existsSync, mkdirSync, appendFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { loadAgent } from '../lib/agent-loader.js';
import { runAgent } from '../lib/runner.js';
import {
  loadEnvLocal, requireEnv, serviceClient, listPublishedIssues, issueUrl, contentHash,
  TOPICS, type Topic,
} from '../lib/social.js';
import type { SupabaseClient } from '@supabase/supabase-js';

const MODEL = process.env.SOCIAL_MODEL ?? 'claude-haiku-4-5-20251001';
const MIN_OUTLETS = Number(process.env.REACTIVE_MIN_OUTLETS ?? '3');
const MAX_PER_TOPIC = Number(process.env.REACTIVE_MAX_PER_TOPIC ?? '5');

interface ClusterRow { id: string; rep_title: string; rep_url: string; outlet_count: number; velocity: number; last_seen: string }

interface ClassifierOut {
  topic: Topic;
  topic_fit: number;
  has_structural_angle: boolean;
  structural_angle: string;
  voice_fit: boolean;
  related_issue_slug: string;
  route: 'ignore' | 'issue-candidate' | 'social' | 'both';
  post?: { body: string; variant: string; mode: string; link_url: string };
  candidate?: { title: string; why_now: string; angle: string; suggested_kinds: string[]; sources: string[]; notes: string };
}

function parseJson(message: string): ClassifierOut {
  let s = message.trim();
  const fence = s.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fence) s = fence[1].trim();
  const a = s.indexOf('{'), b = s.lastIndexOf('}');
  if (a === -1 || b === -1) throw new Error('classifier returned no JSON');
  return JSON.parse(s.slice(a, b + 1)) as ClassifierOut;
}

function candidatePath(topic: string): string {
  const date = new Date().toISOString().slice(0, 10);
  return join(process.cwd(), 'research', topic, `${date}-reactive-candidates.md`);
}

function nextCandidateNumber(path: string): number {
  if (!existsSync(path)) return 1;
  const matches = readFileSync(path, 'utf-8').match(/^## C-\d+/gm);
  return (matches?.length ?? 0) + 1;
}

function appendCandidate(topic: string, out: ClassifierOut): void {
  const c = out.candidate!;
  const path = candidatePath(topic);
  mkdirSync(join(process.cwd(), 'research', topic), { recursive: true });
  if (!existsSync(path)) {
    writeFileSync(path, `# ${topic} — reactive candidates (auto-surfaced from trending news)\n\n> Generated by scripts/reactive/route.ts. Review + merge the worthwhile ones\n> into the live candidates file, then run /pipeline-research. Human-gated.\n\n`);
  }
  const n = String(nextCandidateNumber(path)).padStart(2, '0');
  const kinds = (c.suggested_kinds ?? []).join(', ');
  const sources = (c.sources ?? []).map((u) => `  - ${u}`).join('\n');
  const block = [
    `## C-${n} · ${c.title}`,
    ``,
    `- **status:** open`,
    `- **why now:** ${c.why_now}`,
    `- **angle:** ${c.angle}`,
    `- **suggested kinds:** ${kinds}`,
    `- **sources:**`,
    sources || '  - (add from the cluster)',
    `- **notes:** ${c.notes ?? ''}`,
    ``,
    ``,
  ].join('\n');
  appendFileSync(path, block);
  console.log(`  → candidate C-${n} appended to ${path}`);
}

async function queueReactivePost(supabase: SupabaseClient, out: ClassifierOut): Promise<void> {
  const p = out.post!;
  const issueId = out.related_issue_slug || null;
  const linkUrl = p.link_url || (issueId ? issueUrl(issueId) : '');
  const hash = contentHash(issueId ?? 'reactive', 'reactive', p.body);
  const { error } = await supabase.from('social_posts').insert({
    issue_id: issueId, topic: out.topic, platform: 'x', kind: 'reactive',
    variant: p.variant || 'hook', angle: out.structural_angle || null,
    body: p.body, link_url: linkUrl, content_hash: hash,
    created_by: 'reactive-cron', source_meta: { related_issue_slug: out.related_issue_slug, mode: p.mode },
  }).select('id').maybeSingle();
  if (error) {
    if (error.code === '23505') { console.log('  → duplicate reactive post (dedup) — skipped'); return; }
    throw new Error(`reactive social_posts insert failed: ${error.message}`);
  }
  console.log('  → pending reactive post queued for /admin/social');
}

async function routeTopic(supabase: SupabaseClient, topic: Topic): Promise<void> {
  console.log(`\n=== ${topic} ===`);
  const { data, error } = await supabase
    .from('trend_clusters')
    .select('id, rep_title, rep_url, outlet_count, velocity, last_seen')
    .eq('topic', topic).is('routed_at', null).gte('outlet_count', MIN_OUTLETS)
    .order('outlet_count', { ascending: false }).order('velocity', { ascending: false })
    .limit(MAX_PER_TOPIC);
  if (error) throw new Error(`trend_clusters read failed: ${error.message}`);
  const clusters = (data ?? []) as ClusterRow[];
  if (clusters.length === 0) { console.log('  no trending un-routed clusters'); return; }

  const agent = loadAgent('news-classifier');
  const issues = listPublishedIssues().map((i) => `${i.slug} — ${i.title}`).join('\n');

  for (const cl of clusters) {
    // a few member headlines for context
    const { data: mem } = await supabase
      .from('trend_items').select('title, domain, url').eq('cluster_id', cl.id).limit(6);
    const members = (mem ?? []) as { title: string; domain: string | null; url: string }[];

    const prompt = [
      `Classify this trending ${topic} news cluster for Parallax.`,
      ``,
      `topic: ${topic}`,
      `representative: ${cl.rep_title}`,
      `rep_url: ${cl.rep_url}`,
      `outlets carrying it: ${cl.outlet_count}`,
      `member headlines:`,
      ...members.map((m) => `  - ${m.title} (${m.domain ?? ''}) ${m.url}`),
      ``,
      `published_issues (for de-confliction — link to one rather than duplicate):`,
      issues || '  (none yet)',
      ``,
      `Follow your agent definition. Read research/_voice/_voice-core.md, judge topic-fit + structural angle + voice + safety, and return EXACTLY one JSON object.`,
    ].join('\n');

    let out: ClassifierOut;
    try {
      const res = await runAgent({ agent, prompt, model: MODEL, cwd: process.cwd() });
      out = parseJson(res.finalMessage);
      out.topic = topic;
    } catch (err) {
      console.warn(`  ! classify failed for "${cl.rep_title.slice(0, 60)}": ${err instanceof Error ? err.message : err}`);
      continue;
    }

    console.log(`  • ${cl.rep_title.slice(0, 70)} → ${out.route} (fit ${out.topic_fit})`);
    try {
      if ((out.route === 'social' || out.route === 'both') && out.post?.body) await queueReactivePost(supabase, out);
      if ((out.route === 'issue-candidate' || out.route === 'both') && out.candidate) appendCandidate(topic, out);
    } catch (err) {
      console.warn(`  ! route action failed: ${err instanceof Error ? err.message : err}`);
    }

    await supabase.from('trend_clusters')
      .update({ route_verdict: out.route, routed_at: new Date().toISOString() })
      .eq('id', cl.id);
  }
}

async function main(): Promise<void> {
  loadEnvLocal();
  requireEnv('ANTHROPIC_API_KEY'); requireEnv('PUBLIC_SUPABASE_URL'); requireEnv('SUPABASE_SERVICE_ROLE_KEY');
  const supabase = serviceClient();
  const arg = (process.argv[2] ?? 'all').toLowerCase();
  const topics: Topic[] = arg === 'all' ? [...TOPICS] : [arg as Topic];
  if (arg !== 'all' && !TOPICS.includes(arg as Topic)) {
    console.error(`Usage: npm run reactive:route -- <${TOPICS.join('|')}|all>`); process.exit(1);
  }
  for (const t of topics) {
    try { await routeTopic(supabase, t); }
    catch (err) { console.error(`  ! ${t}: ${err instanceof Error ? err.message : err}`); }
  }
}

const invokedDirectly = process.argv[1] && process.argv[1].endsWith('route.ts');
if (invokedDirectly) {
  main().catch((err) => { console.error('reactive:route failed:', err instanceof Error ? err.message : err); process.exit(1); });
}
