-- Parallax — Social pipeline (evergreen + reactive)
-- Created: 2026-06-21
--
-- Two tables, both ADMIN/CRON-ONLY (never reader-facing):
--   - social_posts : the approval queue. Generated by the evergreen + reactive
--     pipelines (scripts/), reviewed in /admin/social, then posted via the
--     scheduler. Every row starts status='pending' and needs a human approve.
--   - promotions   : append-only ledger of which structural ANGLE each
--     published issue was last promoted with, so the evergreen pipeline rotates
--     to an unused angle and respects a per-(issue,angle) cooldown.
--
-- Security model: these tables are written by service-role cron jobs and read
-- by service-role admin endpoints (adminClient(), which bypasses RLS). They are
-- NOT exposed to anon/authenticated readers. So we ENABLE RLS with NO policies
-- (deny-by-default for anon/authenticated) and grant nothing to those roles.
-- service_role bypasses RLS, so the pipeline + admin surfaces keep full access.

-- Shared updated_at trigger function (idempotent; matches Phase A convention).
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- ── social_posts ──────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.social_posts (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  issue_id      text,                          -- source issue slug (evergreen); NULL for a reactive post not tied to an issue
  topic         text NOT NULL
                CHECK (topic IN ('politics','space','earth','tech','travel','sports')),
  platform      text NOT NULL DEFAULT 'x'
                CHECK (platform IN ('x','linkedin','bluesky','threads','instagram')),
  kind          text NOT NULL
                CHECK (kind IN ('evergreen','reactive')),
  variant       text NOT NULL,                 -- hook | thread | data-card | paradox | quote
  angle         text,                          -- structural angle (evergreen rotation key)
  body          text NOT NULL
                CHECK (length(body) >= 1 AND length(body) <= 4000),
  thread        jsonb,                         -- optional array of follow-up post strings
  link_url      text,                          -- issue URL — posted in the FIRST REPLY, not the body
  alt_text      text,
  image_ref     text,                          -- path/URL of the rendered card (null until rendered)
  image_brief   jsonb,                         -- the brief the card was rendered from
  content_hash  text NOT NULL,                 -- sha256(issue_id|variant|body) — dedup guard
  status        text NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending','approved','rejected','posted','failed')),
  scheduled_at  timestamptz,
  permalink     text,                          -- set after a successful post
  error_log     text,
  created_by    text,                          -- 'evergreen-cron' | 'reactive-cron' | admin email
  source_meta   jsonb,                         -- reactive: trend cluster id, outlets, etc.
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.social_posts IS 'Admin/cron-only social post approval queue (evergreen + reactive). Every row starts pending; a human approves before it posts. Not reader-facing.';
COMMENT ON COLUMN public.social_posts.thread IS 'Optional JSON array of follow-up post strings for native threads.';
COMMENT ON COLUMN public.social_posts.content_hash IS 'sha256(issue_id|variant|body). UNIQUE — prevents re-queuing an identical post (X flags duplicate content as spam).';
COMMENT ON COLUMN public.social_posts.link_url IS 'Issue URL. Posted in the first reply (native-first; in-body links are reach-suppressed on X).';

-- Dedup guard: identical (issue, variant, body) can only be queued once.
CREATE UNIQUE INDEX IF NOT EXISTS social_posts_content_hash_key
  ON public.social_posts (content_hash);

-- Review queue: pending first, oldest-first so the longest-waiting is on top.
CREATE INDEX IF NOT EXISTS social_posts_queue_idx
  ON public.social_posts (created_at ASC)
  WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS social_posts_status_idx
  ON public.social_posts (status, created_at DESC);

CREATE INDEX IF NOT EXISTS social_posts_issue_idx
  ON public.social_posts (issue_id, created_at DESC);

DROP TRIGGER IF EXISTS social_posts_set_updated_at ON public.social_posts;
CREATE TRIGGER social_posts_set_updated_at
  BEFORE UPDATE ON public.social_posts
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.social_posts ENABLE ROW LEVEL SECURITY;
-- No policies, no grants to anon/authenticated: deny-by-default. service_role
-- (cron + admin endpoints) bypasses RLS and retains full access.

-- ── promotions (evergreen rotation ledger) ────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.promotions (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  issue_id        text NOT NULL,
  angle           text NOT NULL,               -- headline-paradox | key-stat | timeline-beat | quote | lyrical-closer
  social_post_id  uuid REFERENCES public.social_posts(id) ON DELETE SET NULL,
  promoted_at     timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.promotions IS 'Append-only ledger: which structural angle each published issue was last promoted with. Drives non-duplicative angle rotation + per-(issue,angle) cooldown in scripts/evergreen/promote.ts.';

CREATE INDEX IF NOT EXISTS promotions_issue_idx
  ON public.promotions (issue_id, promoted_at DESC);

CREATE INDEX IF NOT EXISTS promotions_issue_angle_idx
  ON public.promotions (issue_id, angle, promoted_at DESC);

ALTER TABLE public.promotions ENABLE ROW LEVEL SECURITY;
-- Deny-by-default; service_role only (same model as social_posts).
